### ISSUE TITLE
Problem loading PS

### ISSUE THREAD

**Issue by nielsenmb** [ashleychontos/pySYD#30]
When running on KIC8738809 I encountered a problem when pysyd attempts to read in the power spectrum. 

pysyd run --star KIC8738809 --info info/star_info.csv --mc 200 -vto

The power spectrum and time series both look fine as far as I can tell. 

[KIC8738809_PS.txt](https://github.com/ashleychontos/pySYD/files/7138364/KIC8738809_PS.txt)
[KIC8738809_LC.txt](https://github.com/ashleychontos/pySYD/files/7138367/KIC8738809_LC.txt)

------------------------------------------------------
Target: KIC8738809
------------------------------------------------------
# LIGHT CURVE: 229661 lines of data read
# Time series cadence: 59 seconds
Traceback (most recent call last):
  File "/home/nielsemb/.local/bin/pysyd", line 8, in <module>
    sys.exit(main())
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/cli.py", line 573, in main
    args.func(args)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/pipeline.py", line 29, in main
    run(args)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/pipeline.py", line 93, in run
    count = pipe(args.params['stars'], args)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/pipeline.py", line 131, in pipe
    single = Target(star, args)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/target.py", line 60, in __init__
    self = utils.load_data(self, args)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/utils.py", line 555, in load_data
    args, star, note = load_power_spectrum(args, star)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/utils.py", line 689, in load_power_spectrum
    args, star, note = check_input_data(args, star, note)
  File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/utils.py", line 878, in check_input_data
    star.freq_cs = np.array(star.frequency[args.of_actual-1::args.of_actual])
ValueError: slice step cannot be zero

**Comment by ashleychontos** [comment]
> File "/home/nielsemb/.local/lib/python3.7/site-packages/pysyd/utils.py", line 878, in check_input_data
star.freq_cs = np.array(star.frequency[args.of_actual-1::args.of_actual])
ValueError: slice step cannot be zero

When a light curve _and_ power spectrum are both provided, pySYD automatically computes the oversampling factor. I loaded in the provided data and estimated an oversampling factor of ~0.44. Since the value is less than 1, taking the integer of that is 0 and thus, attempts to take a "slice" of length zero -> causing the error shown.

Are both of the dependent axes in the proper units (i.e. light curve in days and power spectrum in muHz)? If they are, perhaps the arrays got mixed up with another target?
