### ISSUE TITLE
least squares sometimes gets bad initial guess

### ISSUE THREAD

**Issue by nielsenmb** [ashleychontos/pySYD#31]
When running on KIC9787965 I encountered a problem with scipy.optimize.curve_fit. 

It looks to me like the initial guess for the fit doesn't make sense to curve_fit. 

pysyd run --star KIC9787965 --info info/star_info.csv --mc 200 -vto

[KIC9787965_PS.txt](https://github.com/ashleychontos/pySYD/files/7138480/KIC9787965_PS.txt)
[KIC9787965_LC.txt](https://github.com/ashleychontos/pySYD/files/7138481/KIC9787965_LC.txt)

------------------------------------------------------
Target: KIC9787965
------------------------------------------------------
# LIGHT CURVE: 48996 lines of data read
# Time series cadence: 59 seconds
# POWER SPECTRUM: 24606 lines of data read
# PS is critically-sampled
# PS resolution: 0.345294 muHz
------------------------------------------------------
Estimating numax:
PS binned to 195 datapoints
Numax estimate 1: 3470.54 +/- 38956.27
S/N: 0.01
Numax estimate 2: 2593.41 +/- 402.45
S/N: 1.00
Numax estimate 3: 2374.59 +/- 378.81
S/N: 1.00
Selecting model 3
------------------------------------------------------
Determining background model:
PS binned to 424 data points
Comparing 6 different models:
Model 0: 0 Harvey-like component(s) + white noise fixed
Model 1: 0 Harvey-like component(s) + white noise term
Model 2: 1 Harvey-like component(s) + white noise fixed
Model 3: 1 Harvey-like component(s) + white noise term
Model 4: 2 Harvey-like component(s) + white noise fixed
Model 5: 2 Harvey-like component(s) + white noise term
Based on BIC statistic: model 4
 **background-corrected PS saved**
Traceback (most recent call last):
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/bin/pysyd", line 11, in <module>
    sys.exit(main())
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/cli.py", line 573, in main
    args.func(args)
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/pipeline.py", line 29, in main
    run(args)
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/pipeline.py", line 93, in run
    count = pipe(args.params['stars'], args)
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/pipeline.py", line 135, in pipe
    single.run_syd()
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/target.py", line 84, in run_syd
    self.derive_parameters()
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/target.py", line 264, in derive_parameters
    self.fit_global()
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/target.py", line 589, in fit_global
    self.get_numax_gaussian()
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/pysyd/target.py", line 666, in get_numax_gaussian
    gauss, _ = curve_fit(models.gaussian, self.region_freq, self.region_pow, p0=guesses, bounds=bb, maxfev=maxfev)
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 801, in curve_fit
    **kwargs)
  File "/rds/homes/n/nielsemb/.virtualenvs/pysyd/lib/python3.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 808, in least_squares
    raise ValueError("`x0` is infeasible.")
ValueError: `x0` is infeasible.

**Comment by zhikai2515** [comment]
@nielsenmb 
 I have the same problem. How did you solve it？
@ashleychontos 
What requirements does PySyd have for input data？

**Comment by nielsenmb** [comment]
@zhikai2515 it turned out not to be a problem for our analysis. We just needed a small sample to compare uncertainties, so we just picked a few other targets that worked. Sorry I couldn't find a solution!

**Comment by ashleychontos** [comment]
@zhikai2515 the time array must be in units of days and the frequency array must be in microhertz for them to properly work as inputs. I am very close to implementing both time domain and power spectrum normalization utilities! I will look into this in more detail tomorrow!

Please let me know if either of you found workarounds!

**Comment by ashleychontos** [comment]
this has been fixed in recent updated. please do a pip install -U for the newest version.
