### ISSUE TITLE
Code crashes when supplying --keywords

### ISSUE THREAD

**Issue by danxhuber** [ashleychontos/pySYD#45]
------

### Description

Command line code crashes when supplying --keywords. Error can be reproduced by running the default example in the documentation:

pysyd setup
pysyd run --star 1435467 -dv --ux 5000 --mc 200

Error message:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/pysyd/bin/pysyd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/pysyd/lib/python3.10/site-packages/pysyd/cli.py", line 663, in main
    args.func(args)
  File "/usr/local/anaconda3/envs/pysyd/lib/python3.10/site-packages/pysyd/pipeline.py", line 198, in run
    params = utils.Parameters(args=args)
  File "/usr/local/anaconda3/envs/pysyd/lib/python3.10/site-packages/pysyd/utils.py", line 116, in __init__
    self.add_cli(args)
  File "/usr/local/anaconda3/envs/pysyd/lib/python3.10/site-packages/pysyd/utils.py", line 367, in add_cli
    self.check_cli(args)
  File "/usr/local/anaconda3/envs/pysyd/lib/python3.10/site-packages/pysyd/utils.py", line 406, in check_cli
    raise InputError("\nWhen running multiple stars via command line, the number \n of values provided for %s MUST equal the number of stars\n" % each)
pysyd.utils.InputError: <InputError>

Removing --keywords fixes the problem, but limits code functionality. E.g. the following works:

pysyd run --star 1435467 -dv

### Computing

Please provide (by editing) the following information:

 - **OS:** macos
 - **Version:** 6.10.0
 - **Implementation:** command line

### Attachments

**In order to reproduce the issue from our end, please provide *both* the light curve and power spectrum for the relevant target!**<br/>
Crash happens with default example files

------

**Comment by ashleychontos** [comment]
Please upgrade to v6.10.5, where this has been resolved.
