### ISSUE TITLE
Got an value error

### ISSUE THREAD

**Issue by diyiliaoya** [ashleychontos/pySYD#47]
### Discussed in https://github.com/ashleychontos/pySYD/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **ashleychontos** March  6, 2022</sup>
Do you have a general support question or are you experiencing a problem not directly associated with software malfunction? (i.e. need help asteroseismology-ing?) This is the place for you! </div>

Hi [ashleychontos](https://github.com/ashleychontos),

I got an value error when use "pysyd run -- star 302372658":
    self.freq_cs = np.array(self.frequency[self.params['oversampling_factor']-1::self.params['oversampling_factor']])
ValueError: slice step cannot be zero

I got the LC.txt and PS.txt of TIC302372658 with lightkurve. But I got the upper error when I use pysyd to run it.
So how should I do?

**Comment by danxhuber** [comment]
@ashleychontos this is will probably be fixed by implementing #46

**Comment by diyiliaoya** [comment]
> @ashleychontos this is will probably be fixed by implementing #46

Hi ashleychontos,

Thanks for your reply! I modified the source code according to the #46 and it worked.
But I got another error when use "pysyd run -- star 233733505":
Traceback (most recent call last):
  File "/home/lishijie/anaconda3/envs/test/bin/pysyd", line 33, in <module>
    sys.exit(load_entry_point('pysyd==6.10.1a0', 'console_scripts', 'pysyd')())
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/cli.py", line 663, in main
    args.func(args)
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/pipeline.py", line 193, in run
    _pipe(args.stars, params)
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/pipeline.py", line 133, in _pipe
    star.process_star()
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/target.py", line 157, in process_star
    self.derive_parameters()
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/target.py", line 988, in derive_parameters
    self.first_step()
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/target.py", line 1170, in first_step
    self.global_fit()
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/target.py", line 1563, in global_fit
    self.frequency_spacing()
  File "/home/lishijie/anaconda3/envs/test/lib/python3.10/site-packages/pysyd-6.10.1a0-py3.10.egg/pysyd/target.py", line 1747, in frequency_spacing
    l, a = pl.pop(idx), pa.pop(idx)
TypeError: 'NoneType' object cannot be interpreted as an integer
